Changes to requirements.txt (#65)
* Update requirements.txt

Resolving dependency error for "AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'"

* Update requirements.txt

Resolving dependency error for protobuf version